---
# tasks file for ansible-aws-vpn-client
# Install AWS VPN Client on Debian
- name: Install a .deb package for AWS VPN Client
  apt:
    deb: https://d20adtppz83p9s.cloudfront.net/GTK/latest/awsvpnclient_amd64.deb
  when: ansible_os_family == "Debian"
  ignore_errors: true
  tags: ['aws-vpn-client']

# Install the AWS VPN Client on MacOS
- name: Install the AWS VPN Client on MacOS
  homebrew_cask:
    name: aws-vpn-client
    state: present
  when: ansible_os_family == "Darwin"
  ignore_errors: true
  tags: ['aws-vpn-client']